name: Photo gallery
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title/
url: https://raamg.github.io/GridGallery/
author:
    name: RGRGRG
    twitter: #

theme: jekyll-theme-leap-day
