name: Photo gallery
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title/
url: https://iamnii.github.io/GridGallery/
author:
    name: Adjetey Sowah
    twitter: #

theme: jekyll-theme-leap-day